# language: python sets up virtualenv and pip that we don't need.
# omitting language gives us ruby stuff. c seems likely to be a minimal setup.
language: c
env:
  - TRAVIS_PYTHON_VERSION=2.7 TEST_TARGET=tests
  - TRAVIS_PYTHON_VERSION=3.4 TEST_TARGET=tests
  - TRAVIS_PYTHON_VERSION=3.5 TEST_TARGET=tests
  - TRAVIS_PYTHON_VERSION=3.5 TEST_TARGET=packaging
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      env: TRAVIS_PYTHON_VERSION=3.5 TEST_TARGET=packaging
install:
  - printenv | sort
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      MINICONDA_VERSION=2 ;
    else
      MINICONDA_VERSION=3 ;
    fi ;
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      MINICONDA_OS=Linux ;
    else
      MINICONDA_OS=MacOSX ;
    fi ;
    echo "Fetching Python $MINICONDA_VERSION miniconda for $MINICONDA_OS" ;
    wget https://repo.continuum.io/miniconda/Miniconda$MINICONDA_VERSION-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/bin/activate root
  - printenv | sort
  - conda config --set always_yes yes --set changeps1 no
  - conda update -n root conda
  - conda install -n root conda-build
  - conda info -a
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      OS_PACKAGES=libffi ;
    fi ;
    conda create -q -n test-environment python="$TRAVIS_PYTHON_VERSION" pip redis pycrypto bcrypt ipython-notebook bokeh ruamel_yaml anaconda-client requests $OS_PACKAGES
  - source activate test-environment
  - printenv | sort
  - unset CONDA_ENV_PATH # because the older conda in miniconda sets this, confusing some tests
  - export PATH=`echo "$PATH" | sed -e s@"$HOME"/miniconda/bin:@@g`
  - printenv | sort
  - pip install coverage flake8==2.6.2 pep257 pytest pytest-cov yapf==0.6.2 beautifulsoup4 tornado pytest-xdist
  - conda install -y -q -c conda-forge keyring

script:
  - if test "$TEST_TARGET" = tests; then LANG=en_US.UTF-8 python setup.py test; fi
  - if test "$TRAVIS_PYTHON_VERSION" = "3.5" && test "$TEST_TARGET" = "packaging"; then
      git fetch --unshallow ;
      LANG=en_US.UTF-8 python setup.py conda_package ;
    else
      echo "Not building packages on $TRAVIS_PYTHON_VERSION target=$TEST_TARGET" ;
    fi
